using System;

namespace HiRes.Common {

	public enum PaymentTxnResCode {
		OK = 0,
		AUTHORIZATION_FAILED = -1,
		ORDER_DIRECTORY_CREATION_FAILED = -2,
		DB_OPERATION_FAILED = -3,
		NON_AUTHENTICATED_CUSTOMER = -4,
		BILLINGCONTACT_NOTSET = -5,
		TXN_FAILED_GATEWAY = -6,
		CAPTURE_WRONG_AMOUNT_DISTRIBUTION = -7,
		WRONG_PAYMENT_INSTRUMENT = -8,
		WRONG_TRANSACTION_TYPE = -9,
		WRONG_AMOUNT = -10,
		TXNID_NOT_FOUND = -11,
		CAPTURE_OPERATION_CANT_BE_PERFORMED = -12
	}

}
